
[settings]
	#Configures if the block picking behavior should be inverted. When true then a normal middle-click will get the full chiseled block and a shift-middle-click gets the bit. If this is false then the behaviours are swapped.
	invert-pick-block-behaviour = false

	[settings.bit-bag]
		#Should the durability bar display the emptiness of the bag instead of the fullness?
		invert-durability-bar-indication = false

	[settings.placement]

		[settings.placement.render-mode]
			#The render mode of successful placement
			#Allowed Values: GHOST_BLOCK_MODEL, GHOST_BLOCK_MODEL_SOLID_COLOR, WIREFRAME
			success = "GHOST_BLOCK_MODEL"
			#The render mode of failed placement
			#Allowed Values: GHOST_BLOCK_MODEL, GHOST_BLOCK_MODEL_SOLID_COLOR, WIREFRAME
			failed = "GHOST_BLOCK_MODEL_SOLID_COLOR"

		[settings.placement.color]
			#The color of successful placement
			success = [0.1882352977991104, 0.47058823704719543, 0.7882353067398071, 0.7058823704719543]
			#The color of failure due to the block not fitting
			not-fitting = [0.7176470756530762, 0.2549019753932953, 0.054901961237192154, 0.7058823704719543]
			#The color of failure due to a lack of bits or space
			missing-bits-or-space = [1.0, 0.8588235378265381, 0.3450980484485626, 0.7058823704719543]

	[settings.chiseling-previews]
		#Sets which preview renderer is in use. Currently C&B provides: `chiselsandbits:default` (Simple outline rendering) and `chiselsandbits:noop` (No preview) as options.
		renderer = "chiselsandbits:default"

		[settings.chiseling-previews.default]

			[settings.chiseling-previews.default.colors]
				#The color for the chiseling preview outline.
				chiseling = [0.8500000238418579, 0.0, 0.0, 0.6499999761581421]
				#The color for the placement preview outline.
				placement = [0.0, 0.8500000238418579, 0.0, 0.6499999761581421]

		[settings.chiseling-previews.debug]
			#Indicates if the debug rendering in chiseling and placement previews should be enabled.
			enabled = false

			[settings.chiseling-previews.debug.mutator]

				[settings.chiseling-previews.debug.mutator.colors]
					#The color of the chiseling mutation area in the chiseling preview.
					chiseling = [0.0, 0.0, 0.8500000238418579, 0.6499999761581421]
					#The color of the placement mutation area in the placement preview.
					placement = [0.8500000238418579, 0.8500000238418579, 0.0, 0.6499999761581421]

	[settings.selected-tool-mode-icons]
		#Sets which tool mode icon renderer is in use. Currently C&B provides: `chiselsandbits:group` (Render the group icon in the top right corner) and `chiselsandbits:noop` (No icon) as options.
		renderer = "chiselsandbits:group"

	[settings.clipboard]
		#The amount of blocks to keep in the creative clipboard.
		#Range: 0 ~ 64
		size = 64
		#When set to true this adds broken chiseled blocks to the creative clipboard.
		add-broken-blocks = true
		#When set to true this adds picked chiseled blocks to the creative clipboard.
		add-picked-blocks = true

	[settings.patterns]
		#The path where exported patterns should be saved.
		export-path = "./chiselsandbits/patterns"

[performance]

	[performance.caches]

		[performance.caches.sizes]
			#Size of the bit storage inner models cache.
			#Range: 0 ~ 9223372036854775807
			bit-storage-content-models = 100
			#Size of the block model cache.
			#Range: 3500 ~ 20000
			block-models = 10000
			#Size of the model face cache.
			#Range: 350000 ~ 2000000
			block-faces = 1000000
			#Size of the item stack model cache.
			#Range: 0 ~ 9223372036854775807
			stack-models = 100

	[performance.lighting]
		#Should C&B pull lighting values from model faces.
		extract-lighting-values-from-faces = true
		#Should C&B pull lighting values from blockstates.
		extract-lighting-values-from-blockstates = false

	[performance.model-building]
		#How many CPU threads should be used to build models?
		#Range: 1 ~ 8
		thread-count = 4

[gui]

	[gui.radial-menu]
		#Should the mouse indicator be rendered?
		display-mouse-indicator = false

