
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Allows the mod to try to remap and convert other blocks and items from other compat mods that have been uninstalled from one world. This was made so one can uninstall such mods seamlessly having their blocks converted into Evety Compat counterparts
	remap_other_mods = false
	#Clears out and remaps all blocks registered by this mod belonging to uninstalled wood types to air or oak wood
	remap_self = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true

[wood_type]

	[wood_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		crimson = true
		warped = true

	[wood_type.domum_ornamentum]
		cactus = true
		green_cactus = true

	[wood_type.tconstruct]
		greenheart = true
		skyroot = true
		bloodshroom = true

	[wood_type.integrateddynamics]
		menril = true

	[wood_type.forbidden_arcanus]
		fungyss = true
		cherrywood = true
		mysterywood = true
		edelwood = true

	[wood_type.biomesoplenty]
		fir = true
		redwood = true
		cherry = true
		mahogany = true
		jacaranda = true
		palm = true
		willow = true
		dead = true
		magic = true
		umbran = true
		hellbark = true

	[wood_type.architects_palette]
		twisted = true

	[wood_type.byg]
		aspen = true
		baobab = true
		blue_enchanted = true
		cherry = true
		cika = true
		cypress = true
		ebony = true
		fir = true
		green_enchanted = true
		holly = true
		jacaranda = true
		mahogany = true
		mangrove = true
		maple = true
		pine = true
		rainbow_eucalyptus = true
		redwood = true
		skyris = true
		willow = true
		witch_hazel = true
		zelkova = true
		sythian = true
		palm = true
		lament = true
		bulbis = true
		nightshade = true
		ether = true
		imparius = true

	[wood_type.quark]
		azalea = true
		blossom = true

	[wood_type.rocketcraft_simulator_]
		rubber_tree = true

[leaves_type]

	[leaves_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		azalea = true
		flowering_azalea = true

	[leaves_type.integrateddynamics]
		menril = true

	[leaves_type.forbidden_arcanus]
		cherrywood = true
		mysterywood = true
		nuggety_mysterywood = true

	[leaves_type.ars_nouveau]
		blue_archwood = true
		red_archwood = true
		green_archwood = true
		purple_archwood = true

	[leaves_type.tconstruct]
		earth_slime = true
		sky_slime = true
		ender_slime = true

	[leaves_type.biomesoplenty]
		fir = true
		redwood = true
		mahogany = true
		jacaranda = true
		palm = true
		willow = true
		dead = true
		magic = true
		umbran = true
		hellbark = true
		origin = true
		flowering_oak = true
		rainbow_birch = true
		yellow_autumn = true
		orange_autumn = true
		maple = true
		white_cherry = true
		pink_cherry = true

	[leaves_type.architects_palette]
		twisted = true

	[leaves_type.byg]
		aspen = true
		baobab = true
		blue_enchanted = true
		cika = true
		cypress = true
		ebony = true
		fir = true
		green_enchanted = true
		holly = true
		jacaranda = true
		mahogany = true
		mangrove = true
		maple = true
		pine = true
		rainbow_eucalyptus = true
		redwood = true
		skyris = true
		willow = true
		witch_hazel = true
		zelkova = true
		palm = true
		lament = true
		nightshade = true
		ether = true
		araucaria = true
		blooming_witch_hazel = true
		blue_spruce = true
		brown_birch = true
		brown_oak = true
		brown_zelkova = true
		flowering_orchard = true
		flowering_palo_verde = true
		holly_berry = true
		indigo_jacaranda = true
		flowering_jacaranda = true
		flowering_indigo_jacaranda = true
		joshua = true
		ripe_joshua = true
		orange_birch = true
		orange_oak = true
		orange_spruce = true
		orchard = true
		palo_verde = true
		pink_cherry = true
		red_birch = true
		red_maple = true
		red_oak = true
		red_spruce = true
		ripe_orchard = true
		silver_maple = true
		green_apple_skyris = true
		white_cherry = true
		yellow_birch = true
		yellow_spruce = true
		withering_oak = true
		flowering_nightshade = true
		firecracker = true

	[leaves_type.quark]
		blue_blossom = true
		lavender_blossom = true
		orange_blossom = true
		pink_blossom = true
		yellow_blossom = true
		red_blossom = true

	[leaves_type.ars_elemental]
		yellow_archwood = true

	[leaves_type.rocketcraft_simulator_]
		rubber_tree = true

