
[particle_toggles]
	fireflies = true
	sandmote = true
	redsandmote = true
	tumblebush = true
	snow = true
	blizzardwind = true
	blizzardsnow = true
	rain = true
	heavyrain = true
	rainsplash = true
	weepingrain = true
	sporestorm = true
	updrafts = true
	soulstorms = true
	endlessnweather = false
	sandstorms = true
	redsandstorms = true
	blizzards = true
	wind = true

[particle_amounts]
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	particleamount = 32.0
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	particleDensity = 1.0
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	sandmotemodifier = 1.0
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	snowmodifier = 1.0
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	blizzardsnowmodifier = 1.0
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	blizzardwindmodifier = 1.0
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	updraftmodifier = 1.0
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	windmodifier = 1.0
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	sporemodifier = 1.0
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	soulmodifier = 1.0
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	tearmodifier = 1.0
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	rainmodifier = 1.0
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	heavyrainmodifier = 1.0
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	tumblebushmodifier = 1.0
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	fireflymodifier = 1.0

[misc]
	#Range: > -2147483648
	nweatherbasedelay = 120
	#Range: > -2147483648
	nweatherrandomdelay = 240
	renderedweather = false
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	snowspeedmodifier = 1.0

	[misc.block_search_distance]
		#Range: > -2147483648
		x = 32
		#Range: > -2147483648
		y = 32
		#Range: > -2147483648
		z = 32

